title: Ravipati Srinivas
logo: https://github.com/srinivas77777775/RavipatiSrinivas-Portfolio/blob/0b3dd32625128eb685fb9d4abc662be3f373d3de/assets/jngf.jpg
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
